### ISSUE TITLE
Version 1.9.x Magento Upgrade

### ISSUE THREAD

**Issue by res55** [davidalexander/BearsLoveHoney_MultipartAlternativeEmail#1]
Hi David
would you be willing to adjust the code for Version 1.9.x Magento ?

How much would that cost me? I am willing to pay for the work.

Regards
Res

**Comment by davidalexander** [comment]
Hi Res

I'm sorry, this extension has not been worked on since Magento 1.5 and I do not support it. I do hope you can find some who can assist you.

**Comment by res55** [comment]
what a pity.
Do you know of a similar extension for the same problem?

**Comment by davidalexander** [comment]
Afraid not. This extension became somewhat redundant when sites started using third party tools like sendgrid, mandrill and mailgun to send the emails.

**Comment by res55** [comment]
yes, we use also sendgrid, but this does not solve the multipart-problem! Or does it?
